# Generated by Django 3.0.3 on 2020-02-20 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(default='496575233@qq.com', max_length=254, verbose_name='个人邮箱'),
        ),
    ]
