# Generated by Django 3.0.3 on 2020-02-16 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookset', '0003_auto_20200215_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='cxw', max_length=20),
        ),
        migrations.AddField(
            model_name='book',
            name='desc',
            field=models.CharField(blank=True, db_column='description', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='articles',
            field=models.ManyToManyField(related_name='tags', to='bookset.Article'),
        ),
    ]
